
  rest-fights-java11:
    image: quay.io/quarkus-super-heroes/rest-fights:java11-latest
    container_name: rest-fights-java11
    depends_on:
      - fights-db
      - fights-kafka
      - apicurio
      - rest-heroes-java11
      - rest-villains-java11
    ports:
      - "8082:8082"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://fights-db:5432/fights_database
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: none
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
      QUARKUS_REST_CLIENT_HERO_CLIENT_URL: http://rest-heroes:8083
      FIGHT_VILLAIN_CLIENT_BASE_URL: http://rest-villains:8084
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-fights
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
