name: Basic build and test

env:
  MANDREL_VERSION: "23.0.2.1"

on:
  push:
    paths-ignore:
      - '**/deploy/**'
      - '**/*.md'
      - 'docs/**'
      - '**/images/**'
      - '.github/dependabot.yml'
      - '.github/quarkus-ecosystem-test'
      - '.github/workflows/quarkus-snapshot.yaml'
      - '.github/workflows/build-push-ui-images.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - '.github/workflows/sonar-scan.yml'
      - 'scripts/deploy-to-azure-containerapps.sh'
      - 'scripts/watch-services.sh'
      - '**/hyperfoil/**'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - '**/deploy/**'
      - '**/*.md'
      - 'docs/**'
      - '**/images/**'
      - '.github/dependabot.yml'
      - '.github/build-push-container-images*.yml'
      - '.github/quarkus-ecosystem-test'
      - '.github/workflows/quarkus-snapshot.yaml'
      - '.github/workflows/build-push-ui-images.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - '.github/workflows/sonar-scan.yml'
      - 'scripts/*.sh'
      - '**/hyperfoil/**'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
          - rest-narration
          - grpc-locations
          - ui-super-heroes
    name: "build-test-${{ matrix.project }}-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: "build-test-jvm-${{ matrix.project }}-java-${{ matrix.java }}"
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }}

      - name: Build/test with Azure OpenAI
        if: matrix.project == 'rest-narration'
        working-directory: ${{ matrix.project }}
        env:
          QUARKUS_PROFILE: azure-openai
          QUARKUS_TEST_INTEGRATION_TEST_PROFILE: azure-openai
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }}

  native-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
          - rest-narration
          - grpc-locations
          - ui-super-heroes
    name: "native-build-test-${{ matrix.project }}"
    steps:
      - uses: actions/checkout@v4

      - name: Get Mandrel file name
        run: echo "MANDREL_FILE=mandrel-java${{ matrix.java }}-linux-amd64-${{ env.MANDREL_VERSION }}-Final.tar.gz" >> $GITHUB_ENV

      - name: Cache and restore Mandrel distro
        id: check-mandrel-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.MANDREL_FILE }}
          key: mandrel-distro-${{ env.MANDREL_VERSION }}

      - name: Download Mandrel
        if: steps.check-mandrel-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/mandrel/releases/download/mandrel-${{ env.MANDREL_VERSION }}-Final/${{ env.MANDREL_FILE }}"
          wget -q -O ${{ env.MANDREL_FILE }} $download_url

      - name: Setup Maven+OpenJDK Distro
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ env.MANDREL_FILE }}
          java-version: ${{ matrix.java }}
          architecture: x64
          cache: maven

      - name: "build-test-native-${{ matrix.project }}-java-${{ matrix.java }}"
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }} 

      - name: Build/test with Azure OpenAI
        if: matrix.project == 'rest-narration'
        working-directory: ${{ matrix.project }}
        env:
          QUARKUS_PROFILE: azure-openai
          QUARKUS_TEST_INTEGRATION_TEST_PROFILE: azure-openai
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }}
