name: Sonar scan

on:
  workflow_call:
  workflow_dispatch:

jobs:
  sonar-scan:
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
          - rest-narration
          - grpc-locations
          - ui-super-heroes
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      
      - name: Sonar scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }} \
            -Dquarkus.package.write-transformed-bytecode-to-build-output=true \
            -Dsonar.organization=quarkusio-quarkus-super-heroes \
            -Dsonar.projectKey=quarkusio-quarkus-super-heroes_${{ matrix.project }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml,target/jacoco-it-report/jacoco.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.junit.reportPaths=target/surefire-reports
      #            -Dsonar.branch.name=main
